### ISSUE TITLE
Replication code

### ISSUE THREAD

**Issue by andrewschreiber** [adebayoj/sanity_checks_saliency#1]
Interested in replicating this paper. Do you have a new ETA when the code will be available? Thanks!

**Comment by adebayoj** [comment]
Hi @andrewschreiber, thanks for the note. This is my priority for the next few weeks. Latest by end of this week, all of the code should be up here. Apologies for the late reply. I'll ping this issue again shortly.

Thanks!

**Comment by nathanbgaw** [comment]
@adebayoj I am also interested in replicating this paper.  When do you think you will be able to upload the code?

**Comment by robbertstruyven** [comment]
@adebayoj Upvoting this question: very interesting paper to start experimenting with!

**Comment by wildphoton** [comment]
Hi, @adebayoj any good news on the releasing?

**Comment by aum12** [comment]
@adebayoj Checking in on the code release - any ETA?

**Comment by huygens12** [comment]
Hi, @adebayoj any updates on the code releasing?

**Comment by sepehrgolriz** [comment]
Hi @adebayoj 
Is there any chance to get access to the code?

**Comment by adebayoj** [comment]
Hi Everyone. Releasing this code and notebooks has been long due! Super apologies for the extended delay. I am happy to say that I finally pushed a quick replication of the work. Please read the readme to see what the key changes are. Take a look at the notebooks folder to see end-to-end walkthroughs for the key experiment. 

Thanks for the patience!
