### ISSUE TITLE
Query regarding SSIM score

### ISSUE THREAD

**Issue by bnaman50** [adebayoj/sanity_checks_saliency#2]
Hey, 

I found your paper really interesting and was trying to understand it further. I was wondering as to how do you compare the different heatmaps quantitatively using SSIM scores? As per the syntax of SSIM score -  
`skimage.measure.compare_ssim(X, Y, win_size=None, gradient=False, data_range=None, multichannel=False, gaussian_weights=False, full=False, **kwargs)` 
you need to provide the data-range to compare the two heatmaps. 

In the paper, you have mentioned the following - 
> We compute the SSIM and HOGs similarity metric on
ImageNet examples without absolute values.

Based on this, my understanding is that you are computing the SSIM score between two raw heatmaps (without any sort of normalization). Here is what I am trying to figure out - 

- What value do you specify for the data-range?
- If the above point is not correct, are you normalizing the raw heatmaps between `[-1, 1]`?

Your response will be deeply appreciated. 

Thanks, 
Naman

**Comment by adebayoj** [comment]
Hi @champnaman, 

Here are some answers: 
```python
from skimage.measure import compare_ssim as ssim
ss_score = ssim(original_map, randomized_map,  win_size=5, data_range=2) 
```

You are correct, both the original map and the randomized map are normalized to the range [-1,1].
That sentence in the paper should probably have included that we normalized the map to that range. 

I am sure you have some other questions, which code will probably clarify. Please check back by the end of the week for notebooks and other source files. Thanks for your patience. I'll post on this issue once that is done. 

Thanks!
