### ISSUE TITLE
Source Code and SSIM vs HOG similarity for Grad-CAM

### ISSUE THREAD

**Issue by Shubhambindal2017** [adebayoj/sanity_checks_saliency#3]
@adebayoj Is the source code of implementation available?, I saw some issues where the expected date for the code to be uploaded was ~1 year before. 
I also have a doubt after reading the paper, like for almost all metrics ie correlations and similarity, GRAD-CAM (not guided GRAD-CAM) seems to pass all sanity checks, but for SSIM it seems to fail. So how it behaves differently for SSIM as compared to HOG similarity (where it seems to pass the sanity check), and then how should the GRAD-CAM be considered (as overall)?

**Comment by Shubhambindal2017** [comment]
I worked on its implementation and my work can be found here:
[https://github.com/Shubhambindal2017/Unoffical-Implementation-of-GRAD-CAM-with-Sanity-Checks](https://github.com/Shubhambindal2017/Unoffical-Implementation-of-GRAD-CAM-with-Sanity-Checks)

**Comment by adebayoj** [comment]
Thanks for the comment, I have finally update the repo with notebooks and source code to replicate the work. Please take a look and let me know if you have questions. Thanks.

**Comment by adebayoj** [comment]
I am closing this issue. Feel free to re-open if you have any more questions or concerns.
